### ISSUE TITLE
How to use pinned metadata during uv build?

### ISSUE THREAD

**Issue by b4ird** [edgarrmondragon/hatch-pinned-extra#10]
I'm trying to use this plugin to work round the issue described in [this thread](https://github.com/astral-sh/uv/issues/8729). I've added the following to my `pyproject.toml`:

```toml
[build-system]
requires = [
    "hatchling",
    "hatch-pinned-extra",
]
build-backend = "hatchling.build"

[tool.hatch.metadata.hooks.pinned_extra]
name = "pinned"
```

How do I tell `uv` to use this metadata when building my wheel? I've run `uv build` as is and looking at the whl it doesn't look like the deps are pinned.

Cheers!
